# -*- coding: utf-8 -*-
"""apply_augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpD8EEdPJRFIAoWCM8Ir-HJlF-dGFsCW
"""

def apply_augmentation(image, mask):

    def _aug_fn(img_np, mask_np):

        augmented = augment_fn(image=img_np, mask=mask_np)

        return augmented['image'], augmented['mask']

    image, mask = tf.numpy_function(_aug_fn, [image, mask], [tf.float32, tf.float32])

    image.set_shape([H, W, 3])

    mask.set_shape([H, W, 1])


    return image, mask