# -*- coding: utf-8 -*-
"""Compile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fd6tyn2iO0AMZ08m69Amx8q1B4eYtVvO
"""

# ✅ Compile the Model

model.compile(

    optimizer=Adam(learning_rate=initial_lr),

    loss=hybrid_loss,

    metrics=["accuracy", iou_metric, dice_coefficient, Precision(), Recall()]  # Include relevant metrics

)