# -*- coding: utf-8 -*-
"""dice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zsGD2LlO9BVrAOsuU_OTD27LjSuSarx5
"""

def dice_coefficient(y_true, y_pred, smooth=1e-6):

    y_true_f = K.flatten(y_true)

    y_pred_f = K.flatten(y_pred)

    intersection = K.sum(y_true_f * y_pred_f)

    return (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)

def dice_loss(y_true, y_pred, smooth=1e-6):

    return 1 - dice_coefficient(y_true, y_pred, smooth)