# -*- coding: utf-8 -*-
"""iou.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kA8RHznfDGmQYqV-9qsxiOvthhcX8DHe
"""

def iou_metric(y_true, y_pred, smooth=1e-6):

    y_true_f = K.flatten(y_true)

    y_pred_f = K.flatten(y_pred)

    intersection = K.sum(y_true_f * y_pred_f)

    union = K.sum(y_true_f) + K.sum(y_pred_f) - intersection

    return (intersection + smooth) / (union + smooth)


def iou_loss(y_true, y_pred, smooth=1e-6):

    return 1 - iou_metric(y_true, y_pred, smooth)